version: "3.7"

x-app: &web-app
  image: python:3.7.10-slim-buster
  environment: 
    FLASK_ENV: development
    PORT: 10000
  working_dir: /opt/apps/backend
  depends_on:
    - "redis"
  volumes:
    - ./backend:/opt/apps/backend
    - ./frontend/build:/opt/apps/backend/templates
    - ./frontend/build/static:/opt/apps/backend/static

services:
  redis:
    image: "redis:alpine"

  web:
    <<: *web-app
    ports:
      - 5000:5000
    command: >
      bash -c "pip install -r requirements.txt 
      && FLASK_APP=app.py
      && python -m flask run -h 0.0.0.0"

  worker:
    <<: *web-app
    command: >
      bash -c "pip install -r requirements.txt
      && python -m celery -A 'tasks.app' worker --loglevel=INFO"
